name: Deploy to GitHub Pages

on:
 push:
    branches:
      - main
 workflow_dispatch:

jobs:
 deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        uses: actions/github-pages@v4
        with:
          # Specify the folder you want to deploy
          path: 'dist'
          # Specify the branch you want to deploy to
          branch: 'gh-pages'
          # Specify the folder name in the repository
          folder: '.'
